import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import WhatsappButton from "@/components/buttons/WhatsappButton";

const Eurostile = localFont({
  src: [
    {
      path: "./fonts/eurostile.otf",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-eurostile",
});
const HelveticaNeue = localFont({
  src: [
    {
      path: "./fonts/HelveticaNeueLight.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueMedium.otf",
      weight: "500",
      style: "medium",
    },
  ],
  display: "swap",
  variable: "--font-helvetica-neue",
});

export const metadata: Metadata = {
  title: "Ubnet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${HelveticaNeue.variable} ${Eurostile.variable} layout relative w-screen overflow-x-hidden antialiased`}
      >
        <Providers>
          <Header />
          {children}
          <WhatsappButton />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
